spring:
  application:
    name: tacocloud
  datasource:
    name: tacocloud
    generate-unique-name: false
  data:
    rest:
      base-path: /data-api
  jms:
    template:
      default-destination: tacocloud.order.queue
server:
  port: 8081